name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Piepline gets triggered on push or PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt # Install dependencies from requirements.txt

      # Static Analysis with pylint
      - name: Run Static Analysis
        run: |
          pylint main.py --fail-under=8.0  # Set the minimum score for linting pass

      - name: Run Unit Tests and Coverage
        run: |
          pytest --cov=main --cov-fail-under=90 test.py

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Token retrieved securely from GitHub Secrets
